import { EnvironmentVariables } from '@core/config/env.validation'
import { Injectable } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import * as crypto from 'crypto'

import { ENCRYPTION_CONFIG } from './constants/encryption.constant'
import { EncryptionException } from './exceptions/encryption.exception'

@Injectable()
export class EncryptionService {
  private readonly MINIMUM_PAYLOAD_LENGTH =
    ENCRYPTION_CONFIG.IV_LENGTH + ENCRYPTION_CONFIG.AUTH_TAG_LENGTH
  private readonly key: Buffer

  constructor(
    private readonly configService: ConfigService<EnvironmentVariables, true>,
  ) {
    const secret = this.configService.get('TOKEN_ENCRYPTION_KEY', {
      infer: true,
    })
    this.key = crypto.scryptSync(
      secret,
      ENCRYPTION_CONFIG.KDF_SALT,
      ENCRYPTION_CONFIG.KEY_LENGTH,
    )
  }

  /**
   * Encrypts the provided text using the configured algorithm (AES-GCM typically) with a generated IV.
   * The resulting string is base64 encoded and includes the IV and Auth Tag for decryption.
   *
   * @param {string} text - The plain text string to encrypt.
   * @returns {string} - The base64 encoded encrypted string, including IV and Auth Tag.
   * @throws {EncryptionException} - Thrown if the input text is empty or falsy.
   */
  encrypt(text: string): string {
    if (!text) throw new EncryptionException('Text to encrypt cannot be empty')
    const iv = crypto.randomBytes(ENCRYPTION_CONFIG.IV_LENGTH)
    const cipher = crypto.createCipheriv(
      ENCRYPTION_CONFIG.ALGORITHM,
      this.key,
      iv,
    )
    const encryptedBuffer = Buffer.concat([
      cipher.update(text, 'utf8'),
      cipher.final(),
    ])
    const authTag = cipher.getAuthTag()
    return Buffer.concat([iv, authTag, encryptedBuffer]).toString('base64')
  }

  /**
   * Decrypts an encrypted string that was previously generated by the encrypt method.
   * Extracts the IV and Auth Tag from the base64 payload to perform decryption.
   *
   * @param {string} encryptedText - The base64 encoded encrypted string containing IV, Auth Tag, and cipher text.
   * @returns {string} - The original decrypted plain text string.
   * @throws {EncryptionException} - Thrown if the input is empty, has invalid format, or decryption fails.
   */
  decrypt(encryptedText: string): string {
    if (!encryptedText) {
      throw new EncryptionException('Encrypted text cannot be empty')
    }
    try {
      const data = Buffer.from(encryptedText, 'base64')
      if (data.length < this.MINIMUM_PAYLOAD_LENGTH) {
        throw new EncryptionException('Invalid encrypted format')
      }
      const iv = data.subarray(0, ENCRYPTION_CONFIG.IV_LENGTH)
      const authTag = data.subarray(
        ENCRYPTION_CONFIG.IV_LENGTH,
        this.MINIMUM_PAYLOAD_LENGTH,
      )
      const encrypted = data.subarray(this.MINIMUM_PAYLOAD_LENGTH)
      const decipher = crypto.createDecipheriv(
        ENCRYPTION_CONFIG.ALGORITHM,
        this.key,
        iv,
      )
      decipher.setAuthTag(authTag)
      return Buffer.concat([
        decipher.update(encrypted),
        decipher.final(),
      ]).toString('utf8')
    } catch (error) {
      if (error instanceof EncryptionException) throw error
      throw new EncryptionException('Decryption failed')
    }
  }
}
