export const SHAREPOINT_OPERATIONS = [
  'PageViewed',
  'FileAccessed',
  'FilePreviewed',
  'ListViewed',
  'FileAccessedExtended',
  'PageViewedExtended',
  'FileDownloaded',
  'FileSyncDownloadedFull',
  'FileUploaded',
  'FileModified',
  'FileRenamed',
  'FolderCreated',
  'FolderModified',
  'ListItemUpdated',
  'FolderRenamed',
  'FileDeleted',
  'FileRecycled',
  'FolderRecycled',
  'ListItemDeleted',
  'FileDeletedFirstStageRecycleBin',
  'SharingSet',
  'SharingLinkCreated',
  'SharingLinkUsed',
  'AnonymousLinkCreated',
  'SecureLinkCreated',
  'AddedToSecureLink',
] as const

export type SharepointOperation = (typeof SHAREPOINT_OPERATIONS)[number]
