export const SYNC_CONFIG = {
  INITIAL_BACKFILL_DAYS: 7,
  CATCHUP_STEP_DAYS: 1,

  ZERO_LAG_MINUTES: 30,

  RECONCILIATION_LOOKBACK_DAYS: 7,

  MAX_RETRY_PER_ID: 5,

  DB_INSERT_CHUNK_SIZE: 1000,
  CONCURRENT_DOWNLOADS: 15,
  RECONCILIATION_FETCH_CONCURRENCY: 3,
  LOCK_TTL_MS: 30 * 60 * 1000,
  STATE_WATERMARK_KEY: 'sharepoint_audit_forward',
  LOCK_KEY: 'sharepoint_sync_lock',
} as const
